### ISSUE TITLE
Leggje inn kva er nytt i v2-lista på hjelpesida

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#129]

**Comment by zrrrzzt** [comment]
Hva er egentlig nytt...? utover VoIP?
Var ikke så kjent med den gamle, og er klar over at på den tekniske siden er dette noe helt annet, men er vi ikke ganske like bortsett fra at du kan ringe rett fra løsningen :-)

**Comment by madsop** [comment]
https://docs.google.com/document/d/1tx8-PwmQpe0euaFpG9oYuDnMEwMT6KW5ZC0ARlPvMA4/edit#heading=h.r5qn60lcbk1z er eit godt utgangspunkt. Litt utdatert, vi har vel feks lagt på telefonsvarar etterpå.
