### ISSUE TITLE
Håndtere 403 på brukerendringer

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#142]
Noen endringer på brukere returnerer 403 og dette burde gis tilbakemelding på

**Comment by madsop** [comment]
Tippar dette er viss ein godkjenner prøver å endre ein annan godkjenner?

**Comment by madsop** [comment]
Tippar denne utgår til fordel for #159

**Comment by madsop** [comment]
Tar sjansen på å lukke denne, får heller lage ny om vi ser problemet igjen.
