### ISSUE TITLE
Forsinkelse på visningen av manus/skjema på ringesiden

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#147]
- når man bytter visningsmodus på ringesiden ser det ut til at det forrige valget henger igjen

**Comment by madsop** [comment]
Ser ut som vi har det samme på _Mine samtaler_ no. Første gong ser alt fint ut, men viss du byttar fram og tilbake mellom modusane, vil etter kvart alle samtalane bli med.

**Comment by zrrrzzt** [comment]
Jeg har sett det i prod, men det er egentlig ikke skiftet som gjør det. Virker til å være noe state som ikke ryddes opp i siden det alltid fikses ved å besøke en annen side og så gå tilbake.
