### ISSUE TITLE
reCaptcha for login-sida

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#155]

**Comment by zrrrzzt** [comment]
Litt usikker på verdien av å ha dette her.
Man logger seg inn via Hypersys så roboter får ikke opprettet kontoer.
Det er heller ikke data som opprettes vis skjemaet så.... i beste fall kanskje stoppe noen ekstra kall mot en adresse som ikke dukker opp på søkesider?

**Comment by madsop** [comment]
Vi opprettar for så vidt data, men det skjer berre viss HS-innlogginga går bra. Tenkjer kanskje mest mot DDOS, men det er kanskje ikkje reCaptcha det rette verktyget for?

**Comment by madsop** [comment]
Skulle det trengs, får vi heller skru på f.eks. Cloud Armor i gcp.
