### ISSUE TITLE
Ta med telefonnummeret i FAQ

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#157]
Har vært en del spm om hvilket nummer vi ringer fra så da kan vi legge inn 23 50 66 18 et par steder på hjelp-siden

**Comment by madsop** [comment]
Ta også med SMS-nummeret, kanskje? Og noko om telefonsvareren? #scopecreep

**Comment by zrrrzzt** [comment]
sms-avsender nå er `raudt`. Det er først når verving er på banen at det andre sms-nummeret kommer i sving
