### ISSUE TITLE
Seksjon i hjelp om "ææ, eg fekk ein kjip samtale, kva gjer eg"

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#167]
Her tippar eg både Raudt Oslo og andre med erfaring har innspel

**Comment by zrrrzzt** [comment]
Burde også ligge i eller linkes til fra Manuset

**Comment by madsop** [comment]
Såg behovet for ein litt meir generell variant av denne, så laga #170 også. Kan vurdere om det er samme greie eller to forskjellige ting.

**Comment by zrrrzzt** [comment]
overtas av #182
