### ISSUE TITLE
Sperret siden

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#18]
Lage en side for de som ikke er godkjent ennå eller som er deaktivert

**Comment by madsop** [comment]
Det vil gjera registreringsflyten lettare også. Som det er no kjem du vel rett inn i sentralen når du loggar inn første gong, men utan at du da har fått rolla ringer. Da er det litt unaturleg som brukar å tenkje at du må vente på noko før du kan starte å ringe.
