### ISSUE TITLE
Kopiere områdene fra felleskapfungerer inn i en variant av minipollen

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#196]

**Comment by madsop** [comment]
Skjønner ikkje heilt denne, men det håper eg du gjer 😄

**Comment by zrrrzzt** [comment]
Det er egentlig "hva er viktig for deg" biten fra fellesskapfungerer inn så man kan krysse av på minipoll-style når man ringer...tror jeg
