### ISSUE TITLE
Sende ping til serveren så tidleg som mogleg

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#207]
For å starte opp serveren før brukaren klikkar logg inn og dermed må vente på server-oppstart (som rett nok er ein liten andel av tida samanlikna med HS-kallet)

**Comment by zrrrzzt** [comment]
Gir du meg en egnet ping-url?

**Comment by madsop** [comment]
Tja, du kan bruke /health/live.

**Comment by zrrrzzt** [comment]
den gir 401 unauthorized såvidt jeg kan se.
Kan fint pakke den inn, men er ryddigere om jeg får en som kan kalles og gir 200 når den er våken
