### ISSUE TITLE
Kolonne på brukere-sida for når registrert

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#226]
For å sleppe å hente fram dette i databasen + synleggjera det om nokon har vorte liggjande lengje.

**Comment by zrrrzzt** [comment]
Ligger timestamp med i data pr i dag?
Er det også med sist endret dato?
Hvor lenge skal noen ligge før vi kaster på en alarm på toppen av siden?

**Comment by madsop** [comment]
Ser at timestamp ikkje ligg i responsen i dag. Men det ligg i databasen, så bør vera greitt å sende det med.

Nei, sist endra-dato har vi ikkje. Vi har derimot historikk på godkjenningar, om det er interessant. Da med godkjenner, godkjent, ny rolle og tidspunkt.

**Comment by zrrrzzt** [comment]
kan starte med opprettet/registrert timestamp og se hva vi ønsker evt senere :-)
