### ISSUE TITLE
Mine samtaler ser rar ut på mobil

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#24]
Menyen fyllar ikkje heile breidda

**Comment by zrrrzzt** [comment]
Velger nok ikke å prioritere dette så veldig høyt i første omgang. Tror ikke mobil er anbefalt arbeidsverktøy på denne løsningen.

**Comment by madsop** [comment]
Einig i den vurderinga. Men vi bør kanskje sjekke det også på nettbrett, det kan vel faktisk ein del finne på å bruke.

**Comment by zrrrzzt** [comment]
spennende med VoIP der ja...
