### ISSUE TITLE
Formatér tidspunkt for ringing i Mine samtaler

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#25]
Å ha tidels sekund er nok unødvendig.

Tenkjer vi dessutan kan ha formatet 28. februar 2021 heller enn 2021-02-28

**Comment by zrrrzzt** [comment]
trenger vel heller ikke årstall med mindre det er et annet år enn det man er i :-)
kan hente inn min standard prettyprint-dato funksjon
