### ISSUE TITLE
Handtere at Hypersys kan vera nede

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#26]
No i kveld er pålogging til (test-)Hypersys nede, både på nettsida deira og i API-et.

Vi bør ta høgde for at det kan skje, og i så fall vise ei fornuftig feilmelding.

Per no kan vi ta ned kun innlogging, men om vi skal leggje opp til å ringe medlemmar, blir det eit issue også for ringinga.

**Comment by madsop** [comment]
Backenden gir no 503 viss pålogging mot Hypersys feila på noko anna enn invalid token.

**Comment by zrrrzzt** [comment]
Kan ta den når jeg tar håndterer de andre feilmeldingene rundt innlogging.

Nedetid på Hypersys er vel regulert etter en eller annen avtale så jeg vet ikke helt hvor langt vi skal strekke oss for å lage 100% fungerende fallback på resten av systemet nå.

**Comment by madsop** [comment]
Nei, og det kan jo vera at testinstansen er meir ustabil enn dei andre også. Så kanskje vi kjem langt med å dekkje innlogging.

**Comment by zrrrzzt** [comment]
Denne er forsåvidt løst via #19 
Gir nå en feilmelding ved 403 og en annen ved 503

**Comment by madsop** [comment]
No i kveld seier hypersys at "Hypersys er nede for vedlikehold", så da fekk eg testa denne, og det fungerer akkurat som det skal.

**Comment by zrrrzzt** [comment]
Ga feilmeldingen mening, eller skal vi iterere en runde over den?

**Comment by madsop** [comment]
Eg syntes den var kurant, så tenkjer vi kan la den vera inntil nokon eventuelt klagar på det.
