### ISSUE TITLE
NEXT_PUBLIC_ variablene funker ikke på GCP

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#29]
Går til gcp-url/undefined/auth/reset heller enn til hypersys/auth/reset

**Comment by zrrrzzt** [comment]
Skrev om tittel til matche det som må fikses :-)

**Comment by zrrrzzt** [comment]
Mulig dette hjelper: https://github.com/vercel/next.js/discussions/13427

NEXT_PUBLIC_* må settes buildtime, det vil si at når docker bygges for gcp må variablene var tilgjengelige for Docker.

Mulig dette plutselig havnet mer i din gate enn min @madsop :-) Altså at noe må inn i gcp-byggescriptet

**Comment by madsop** [comment]
Trur eg rekk å fikse denne før landsmøtestart i dag :wink:
