### ISSUE TITLE
Vise ein slags statistikk for alle som ringer

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#30]
Feks sjå totalt antal samtalar og nokre andre ting frå dagens statistikk

**Comment by madsop** [comment]
Tippar vi kan ta delar av dagens /statistikk/statistikk. Usikker på om det er greiast å lage eit nytt endepunkt backend, eller å returnere forskjellige resultat basert på rolle.

**Comment by zrrrzzt** [comment]
Jeg stemmer for samme endepunkt og bare litt ulikt innhold etter rolle
