### ISSUE TITLE
Gløymt passord-funksjonalitet

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#4]
Kan sende folk rett til hypersys-sin på baseurl/auth/reset/, trur eg.

Usikker på om det er eit poeng å ha hypersys-baseurl-en kun éin plass, og at frontenden dermed bør spørre backend om å få lenka, eller om vi kan tillate oss å ha hypersys-baseurl både i frontend og backend. Eg heller vel mest mot at sistnemnte er greitt.

**Comment by zrrrzzt** [comment]
Vi dobler opp for alle penga :-)
