### ISSUE TITLE
Hent neste feilar etter avslå

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#44]
Loggar inn, går på ring-fana, hentar neste, får opp ei and eg ikkje vil snakke med, avslå samtale. No gir ikkje hent neste person å ringe-knappen lenger restpons.

Å manuelt skrive inn nummer fungerer.

**Comment by zrrrzzt** [comment]
Denne klarer jeg ikke å reprodusere lokalt. Hvilken instans skjer det på?

**Comment by madsop** [comment]
Lukkar denne, får heller gjenopne om vi får gjenskapt det på GCP.
