### ISSUE TITLE
500 på ringemanus 5 på GCP-test

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#45]
Dvs 

Default
2021-03-13 12:07:37.931 CET[Error: ENOENT: no such file or directory, open '/app/ringemanus/fallback.md'] {
Default
2021-03-13 12:07:37.931 CET errno: -2,
Default
2021-03-13 12:07:37.931 CET code: 'ENOENT',
Default
2021-03-13 12:07:37.931 CET syscall: 'open',
Default
2021-03-13 12:07:37.931 CET path: '/app/ringemanus/fallback.md'
Default
2021-03-13 12:07:37.931 CET}
Error
2021-03-13 12:07:37.932 CET GET 500 382 B165 msChrome 89 /api/ringemanus?manus=5

**Comment by madsop** [comment]
Hadde forventa at fallback skulle visast - det visast på vercel-versjonen, og var synleg på GCP også, iallfall i går.

**Comment by zrrrzzt** [comment]
Dersom den vises lokalt og på vercel så må vi vel nok en gang se hva som er spesifikt for gcp.
Alternativt se om det er nor forskjell dersom den kjøres i docker.

Kallet som kjøres er `path.join(process.cwd(), 'ringemanus')`

**Comment by madsop** [comment]
Får 500 internal server error på /api/ringemanus, men 404 på /api/ringemanus/fallback.md

**Comment by zrrrzzt** [comment]
404 er riktig du må sjekke på api/ringemanus?manus=fallback

Utfordringen er åpenbart at noe på gcp gjør at løsningen ikke få lest fra mappen hvor filene ligger eller at den blir presentert for feil opplysninger på hvor den kjøres

**Comment by zrrrzzt** [comment]
hmm, kan være webpack som ikke tar med .md i byggeprosessen tro....

**Comment by zrrrzzt** [comment]
stoler på den og at det er "magi" som fikser det på vercell og lokalt
da kan det tenkes vi må kopiere med litt mer etter bygget om vi skal bruke samme metode

**Comment by madsop** [comment]
> stoler på den og at det er "magi" som fikser det på vercell og lokalt
> da kan det tenkes vi må kopiere med litt mer etter bygget om vi skal bruke samme metode

Kan sjå litt sånn ut. Kan eventuelt prøve ein copy . . for å få med alt, og sjå om det fiksar biffen.
