### ISSUE TITLE
Legge inn mulighet til å switche mellom ulike ringemodus

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#53]
- default til medlemmer men kan switche til velgere
- setter modus i grensesnittet og lagrer i session
- sender valgt modus med til backend i form av ?? når ny samtale skal hentes

**Comment by madsop** [comment]
Trur vi bør defaulte til velgere - det er dei vi har ambisjonar om å ringe klart flest av 😉
