### ISSUE TITLE
Håndtere andre responser enn 200, 401 og 403 fra neste

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#59]
ved 204 blir den stående og spinne i stedet for å si at det ikke er flere å ring

**Comment by madsop** [comment]
Når vi går over til å kunne ringe i heile fylket, blir denne litt mindre sannsynleg, så går litt ned på prioriteringslista.

**Comment by madsop** [comment]
Ser ut som det samme skjer også ved 500.
