### ISSUE TITLE
Visualisere at twilio-samtalen er starta når brukaren har klikka ring

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#79]
Sia det tar nokre sekund før brukaren merkar at det "skjer noko", vil det vera bra med ein indikasjon på at samtalen startar.

**Comment by zrrrzzt** [comment]
Den der har jeg grublet noen runder på. Jeg skifter farge på ikonene på voip, men start sesjon/samtale har jeg valgt å la være manuell.

Dels for å ha færrest mulig bevegelige deler, men også for å gjøre det mulig å enkelt veksle mellom voip og trad. telefon som backup.
