### ISSUE TITLE
Handtere 401 på login

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#80]
Backenden kastar no 401 viss brukaren som prøver å logge inn ikkje har rolle bruker eller venter_paa_godkjenning. Frontend bør vise denne på fornuftig vis.

Kan for så vidt vurdere om det er meir formålstenleg med ein annan HTTP-kode, men trur 401 passar bra.

**Comment by zrrrzzt** [comment]
401 er helt ok. Forslag til tekst?

**Comment by madsop** [comment]
"Du har ikke bruker i systemet. Kontakt oss hvis du meiner at det er feil" eller noko sånt?

**Comment by zrrrzzt** [comment]
samt slenge på en "eller venter på godkjenning" elns også?

**Comment by madsop** [comment]
Nei, for ved venter på godkjenning skal du vel få logga inn? Det er iallfall ikkje omfatta av handteringa backend for denne.

**Comment by zrrrzzt** [comment]
Så egentlig feil er at de ikke har bruker i HyperSys?

**Comment by madsop** [comment]
Ja, sannsynlegvis. Alternativt at vi har kåla til noko programmatisk/i databasen.
