### ISSUE TITLE
Skal dashboard vera på lokallag- eller fylkesnivå?

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#82]
Og skal ein ringar kunne sjå dashboard for både sitt lag og dei andre i fylket?

**Comment by zrrrzzt** [comment]
jeg tenker det, men mulig andre har sterke meninger om at slikt skal være lukket

**Comment by madsop** [comment]
Trur iallfall eg vil ha det som ei liste, heller enn aggregert som no.

**Comment by zrrrzzt** [comment]
Nå vises alt som en liste og jeg tenker kanskje umiddelbart at for admins kan vi vise aggregert og for alle andre hele listen.
Vet ikke hvor mange lag det typisk er pr fylke, men det er i det minste mer overkommelig enn slik det er nå for admins :-)

**Comment by madsop** [comment]
Einig i at det vart veldig mange, men eg synes det er fint med nettopp den detaljerte oversikta. Aggregert data tenkjer eg ein får fint på statistikk-sida.

**Comment by zrrrzzt** [comment]
okay, er denne da greit håndtert så issue kan lukkes?

**Comment by madsop** [comment]
Ja, eg tenkjer det. Så får vi heller lage ny om det trengs.
