### ISSUE TITLE
Legge inn funksjonalitet for tilbakemeldinger

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-frontend#95]
Skulle vi hatt muligheter for tilbakemeldinger i løsningen?

Det er raskt gjort å sette opp f.eks. et lukket repo på GitHub og poste tilbakemeldinger som issues til repoet.

**Comment by madsop** [comment]
Lurt å tenkje på det, iallfall. Og om vi trur det vil gi oss andre/fleire tilbakemeldingar enn å få det på Slack. Eller å sende folk hit, for dei teknisk kyndige/komfortable brukarane (tippar vi har ein god del av dei også).

**Comment by zrrrzzt** [comment]
La inn en standard 1 - 5 komponent i første omgang og viser den på logg ut siden.

Da får vi finger i været følelsen i alle fall.

**Comment by zrrrzzt** [comment]
<img width="1150" alt="Screenshot 2021-03-28 at 09 18 25" src="https://user-images.githubusercontent.com/2197936/112745148-9c074f80-8fa6-11eb-9aee-10c4164981cf.png">

**Comment by zrrrzzt** [comment]
Denne er håndtert greit nå mener jeg. Får heller åpne ny issue om vi ønsker å utvide
