### ISSUE TITLE
Deaktivere knappane på brukere-sida for admins

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#96]
I dag ser det i GUI-et ut som du kan endre på admins. Det kan du ikkje (får 403).

(Nice to have)

**Comment by madsop** [comment]
Alternativ løysing kan vera å vise fram 403-en til brukaren.

**Comment by zrrrzzt** [comment]
Antar det er enklest å ta det bort og evt legge inn igjen om vi ønsker :-)

**Comment by zrrrzzt** [comment]
<img width="1247" alt="Screenshot 2021-03-28 at 07 06 12" src="https://user-images.githubusercontent.com/2197936/112743039-2f835500-8f94-11eb-9e10-d02b7a5e62d1.png">

Jeg får ikke utseendet du beskriver til å matche med GUIet slik jeg ser det. Snakker vi om samme side?

**Comment by madsop** [comment]
Samme side, men forbi kvarandre lell. Tenkjer på desse knappane.
![image](https://user-images.githubusercontent.com/1844557/112748732-0c6d9b00-8fbe-11eb-8162-ee476d0b184c.png)

**Comment by zrrrzzt** [comment]
men ingen av de går på admin vel. det er bruker (for å kunne håndtere avslag til de som ennå ikke er godkjent), ringer og godkjenner. Admin lå der tidligere, men ble fjernet.

Eller er "Godkjenner" og admin det samme?

**Comment by madsop** [comment]
Det har du rett i. Men eg skulle gjerne sett dei knappane deaktiverte når personen er admin.

**Comment by zrrrzzt** [comment]
....og der forstod jeg omsider hva du mente 🤦🏻
